import 'dart:core';

class Dimens {
  static const double btmSwitchSmallW = 100;
  static const double btmCellsH = 200;
  static const double btmCellsW = 300;

  static const double btmChapterH = 220;
  static const double btmLessonH = 205;
  static const double btmGroupH = 190;
  static const double btmActionH = 175;

  static const double btmSwitchBigW = 250;
  static const double actionBtnW = 45;
  static const double pnlToolsW = 250;
  static const double pnlAddsOnW = 650;
  static const double btnHelpW = 27;
  static const double pnlBottomH = 30;
  static const double actionBtnH = 50;
  static const double reviewHeight = 70;
  static const double libIconSize = 40;
  static const double suggestBoxSmallSize = 200;
  static const double libTagSize = 30;
  static const double libTabSize = 627;
  static const double langBtnW = 73;
  static const double langBtnH = 73;
  static const double tabHeight = 43;
  static const double tabNormalW = 150;
  static const double tabSmallW = 60;
  static const double tabBigW = 200;
  static const double flagW = 40;
  static const double topBarHeight = 40;
  static const double actionRadius = 5;
  static const double actionIcon = 21;
  static const double btnWidthNormal = 80;
  static const double btnWidthBig = 150;
  static const double btnHeightNormal = 24;
  static const double btnHeightSmall = 20;
  static const double pointCircle2X = 60;
  static const double pointCircleX = 45;
  static const double pointCircle = 30;
  static const double smallProfileImage = 45;
  static const double midProfileImage = 60;
  static const double bigProfileImage = 75;
  static const double dialogTitleBarHeight = 55;
  static const double dialogSmallWidth = 380;
  static const double dialogNormalWidth = 500;
  static const double dialogBigWidth = 600;
  static const double dialogLargeWidth = 800;
  static const double dialogSmallHeight = 220;
  static const double dialogNormalHeight = 350;
  static const double dialogLargeHeight = 410;
  static const double dialogBigHeight = 550;
  static const double dialogXLargeHeight = 700;
  static const double dialogCornerRadius = 10;
  static const double dialogBottomSize = 53;
  static const double dlgLangHeaderHeight = 53;
  static const double dlgLangItemHeight = 45;
  static const double recordPnlHeight = 60;
  static const double recordPnlWidth = 200;
}
